#define ORGAN_SLOT_TAUR_BODY "taur_body"
#define ORGAN_SLOT_PENIS "penis"
#define ORGAN_SLOT_TESTICLES "testicles"
#define ORGAN_SLOT_BREASTS "breasts"
#define ORGAN_SLOT_BELLY "belly"
#define ORGAN_SLOT_VAGINA "vagina"
#define ORGAN_SLOT_BUTT "butt"
